### ISSUE TITLE
地图上不显示资源

### ISSUE THREAD

**Issue by Chocky1126** [GengGode/GenshinImpact_AutoMap#12]
大佬 我可以正确跟踪地图  但是不能显示资源和跟踪  ALT+F  ALT+M也不行是什么问题啊
![image](https://user-images.githubusercontent.com/50670134/110567825-1190b480-818d-11eb-8340-4dc4915cf8f4.png)

**Comment by GengGode** [comment]
右下角的图标可以点开，选择资源

**Comment by Chocky1126** [comment]
有了有了
