### ISSUE TITLE
东西用不了

### ISSUE THREAD

**Issue by Ajing4152** [GengGode/GenshinImpact_AutoMap#13]
教程麻烦请详细一点，一步一步来，你这的介绍我只看到了你只展示了功能，并没有详细教程，b站的视频也没了。我出现的问题是alt+t之后，人标在跳动，也没有你展示出来的效果，选择原神窗口这个不会用，也不知道怎么用，因为我是全屏，如果点击了游戏窗口就会直接进游戏。

**Comment by GengGode** [comment]
emmm,需要修改快捷方式吗，视频这两天重做

**Comment by Ajing4152** [comment]
-popwindow那个东西也加在快捷方式里面了，也是无效果，就指标在微微跳动。

**Comment by GengGode** [comment]
原神应该不会再缩下去了才对，这样就可以f8选择游戏窗口了，是手柄玩家吗，1920*1080+键盘才有效，

**Comment by Ajing4152** [comment]
电脑玩家，外接了键盘，alt+F8选择窗口选不了原神…点了原神就是进入游戏里面了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月16日(星期二) 晚上10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GengGode/GenshinImpact_AutoMap] 东西用不了 (#13)




 
原神应该不会再缩下去了才对，这样就可以f8选择游戏窗口了，是手柄玩家吗，1920*1080+键盘才有效，

**Comment by GengGode** [comment]
点了进原神就行了应该,如果追踪还没有反应的话麻烦截个图,他可能是没有识别到,你可以试下在开了追踪之后拖动地图,如果他会自动回到原处那就是没有识别出来当前位置,emmm,无论怎样,如果能截图看一下最好了

**Comment by sexchen** [comment]
我选择了窗口 但是程序没有任何反应  地标一直再篱月港 没动过
