### ISSUE TITLE
Doesn't automatically recognize my UID

### ISSUE THREAD

**Issue by EmirhanAsik** [GengGode/GenshinImpact_AutoMap#17]
what should I do ?

**Comment by GengGode** [comment]
https://www.bilibili.com/video/BV1Wy4y1x754，sorry，最近忙于实习，没时间看，这个是前段时间抽空录的，凑合着看下，计划更新在原神1.5版更新之后

**Comment by EmirhanAsik** [comment]
i  try but its not work and i dont have 1920 * 1080 windowed i just have 1920 * 1080 fullscreen
its dont dedect my uid

sorry my bad English :(

**Comment by GengGode** [comment]
这个需要无边框的原神，通过修改原神的exe的快捷方式实现，如果你有QQ的话可以加QQ群，或者通过邮箱联系我，有时间的话可以远程调试下。
This requires the original God without borders, which can be realized by modifying the shortcut of the original God's exe. If you have QQ, you can add QQ group, or contact me through the mailbox. If you have time, you can debug remotely.

另外，我的英语也不好， bad English too me.

**Comment by EmirhanAsik** [comment]
I tried but I could not register QQ , I live in Turkey, I do not know any chinese

**Comment by GengGode** [comment]
啊，那这就只能邮箱联系了。首先要找到GenshinImpact.exe的位置，右键发送快捷方式到桌面，然后修改这个快捷方式，像md文件里说的那样。这样启动就应该没有问题了

Ah, then we can only contact by email。
The first thing is to find out GenshinImpact.exe Right click to send the shortcut to the desktop, and then modify the shortcut, as described in the MD file. So there should be no problem starting
方便的话截个图，
If it's convenient, cut a picture,

**Comment by EmirhanAsik** [comment]
![Capture](https://user-images.githubusercontent.com/70341302/115614485-709e2900-a2f6-11eb-9f7b-886a2e330a32.PNG)
i already did that

**Comment by GengGode** [comment]
那应该可以的啊，那能来张悬浮窗的截图吗，
That should be OK. Can I get a screenshot of the floating window

**Comment by GengGode** [comment]
有可能是没有识别到原神窗口的名称，按Alt+F8弹出选择句柄窗口，选中原神窗口，确定之后在看下
It is possible that the name of the original God window is not recognized. Press Alt + F8 to pop up the selection handle window. Select the original God window, and then click OK

**Comment by EmirhanAsik** [comment]
I already tried it didn't work

**Comment by GengGode** [comment]
UID is 00000 or other？

**Comment by EmirhanAsik** [comment]
00000

**Comment by GengGode** [comment]
我这里有一个调试版，但是太大了，发不了
I have a debug version here, but it's too big to send

**Comment by EmirhanAsik** [comment]
okay if i give a gmail address?

**Comment by GengGode** [comment]
you try onclick Alt+M AutoMap Loacl wall Create a png ,may

**Comment by GengGode** [comment]
i could try a once

**Comment by EmirhanAsik** [comment]
![Uploading Capture2.PNG…]()

**Comment by EmirhanAsik** [comment]
![Uploading Capture.PNG…]()

**Comment by EmirhanAsik** [comment]
![Capture](https://user-images.githubusercontent.com/70341302/115619768-fa50f500-a2fc-11eb-9ef5-b5a4c13c784f.PNG)
![Capture2](https://user-images.githubusercontent.com/70341302/115619972-43a14480-a2fd-11eb-86e2-77e838dec35c.PNG)

**Comment by GengGode** [comment]
emmm
Very Very strange,No Should this,
if you Alt+M could create New Png ? On AutoMap.exe Folder

**Comment by EmirhanAsik** [comment]
alt + m basıyorum hiçbirşey olmuyor

**Comment by EmirhanAsik** [comment]
![Capture](https://user-images.githubusercontent.com/70341302/115621640-7a785a00-a2ff-11eb-9375-4563cf807326.PNG)
this ?

**Comment by GengGode** [comment]
emmm，you need new exe ，but it size as 25MB，you emial is what？

**Comment by EmirhanAsik** [comment]
emirhanasik2005@gmail.com

**Comment by GengGode** [comment]
send done

**Comment by EmirhanAsik** [comment]
I haven't received a mail yet

**Comment by GengGode** [comment]
emmm Mail blocked?，Is there any other way to get in touch

**Comment by EmirhanAsik** [comment]
you have discord ?

**Comment by GengGode** [comment]
loading download ，install ing。。。

**Comment by EmirhanAsik** [comment]
ok

**Comment by GengGode** [comment]
im ok， i m YuSuiXian#5335

**Comment by imaegoo** [comment]
这聊天记录把我给看乐了
