### ISSUE TITLE
自己编译少头文件啊

### ISSUE THREAD

**Issue by daofeng2015** [GengGode/GenshinImpact_AutoMap#18]
![image](https://user-images.githubusercontent.com/14891398/116004536-ad8b5800-a635-11eb-8c44-da50fe5af5f8.png)
qt基本配完配完了.opencv的也解决了..就少了这几个头文件...

**Comment by GengGode** [comment]
需要先编译.ui文件，在解决方案管理器里选中ui文件，右键编译，选中解决方案，右键重新加载解决方案
