### ISSUE TITLE
作者 雷神瞳我找了60多个  然后下午吃完饭开电脑玩的时候发现之前找过的图标又显示  蒙圈了

### ISSUE THREAD

**Issue by cyolc932** [GengGode/GenshinImpact_AutoMap#21]
[](url)
![1](https://user-images.githubusercontent.com/46415893/126938135-b5f6bc94-ebf3-414f-9f9c-d0d6aa1500b0.png)
![2](https://user-images.githubusercontent.com/46415893/126940510-22852c3a-6624-4f1e-bd13-8cb38712a755.jpg)

**Comment by cyolc932** [comment]
我的神童数量
![2](https://user-images.githubusercontent.com/46415893/126938782-204b3b08-ad45-4164-a597-bb08396b8733.jpg)

**Comment by cyolc932** [comment]
45个 麻木了 这个可以帮忙解决一下吗  就是那45个雷神童 显示在地图上了。。。我就只用过这个软件。按键只按了ALT+T

**Comment by GengGode** [comment]
怪了，你看下 C:\Users\%USERNAME%\AppData\LocalLow\天理系统\悬浮窗自动地图 目录下的ini存档文件，应该会有两个的

**Comment by GengGode** [comment]
用新版开过之后会改存档文件结构，别用旧版再开

**Comment by GengGode** [comment]
![image](https://user-images.githubusercontent.com/47711102/126951157-4b60579d-bfcd-4112-9c09-f360a2191d12.png)
0 是没动，1 是见过，2是拿了

**Comment by cyolc932** [comment]
泪目 这次直接打不开了  全程无反应  唉 我还是一个一个看视频找神瞳了
打开全是0

**Comment by GengGode** [comment]
不是吧，路径里没文件？？？

**Comment by cyolc932** [comment]
![image](https://user-images.githubusercontent.com/46415893/126988000-ddf1e804-feac-4bc5-8e8f-3327bfa41ae6.png)
![image](https://user-images.githubusercontent.com/46415893/126988038-6ad57dfc-9005-49ad-8e80-64b83abd01f2.png)
![image](https://user-images.githubusercontent.com/46415893/126988193-db5d986f-5f7b-4418-b62e-fd909bb6306d.png)
  我截图了 有一个全是0 另一个不是  有两个ini文件

**Comment by GengGode** [comment]
uid全0 是默认的不用管，啊这，我裂开了

**Comment by GengGode** [comment]
是什么情况下打开的？不应该会覆盖没啊

**Comment by cyolc932** [comment]
一直用的天理启动器，，，没有别的修改 我打完就退游戏关电脑了  玩的时候就打开电脑 打开天理启动器

**Comment by GengGode** [comment]
悬浮窗是直接关了的？

**Comment by GengGode** [comment]
对不起啊，应该是我的锅，非常抱歉
![4`C1 3U84JXW)$PTP}@}DMD](https://user-images.githubusercontent.com/47711102/126990008-fd4cfd4c-e234-442a-9631-1876b9dd8666.jpg)
我会尽快修复这一bug
