### ISSUE TITLE
上传一下release？

### ISSUE THREAD

**Issue by wmyfelix** [GengGode/GenshinImpact_AutoMap#22]
百度云不太方便，奶牛快传这类的也可以，或者把workflow配置一下自动编译

**Comment by GengGode** [comment]
现在有个近100mb的大图，传不上去，就卡在这了，要是能传上来我就自动构建了
![WVGFUXNPB)%3 @L$ 5)4`F](https://user-images.githubusercontent.com/47711102/126986535-60a65315-28f5-4b78-a632-b94a4cd8c921.jpg)
要不加群吧，群文件里都有，还有沙雕群友作陪，<(￣︶￣)↗[GO!]

**Comment by wmyfelix** [comment]
> 现在有个近100mb的大图，传不上去，就卡在这了，要是能传上来我就自动构建了
> ![WVGFUXNPB)%3 @L$ 5)4`F](https://user-images.githubusercontent.com/47711102/126986535-60a65315-28f5-4b78-a632-b94a4cd8c921.jpg)
> 要不加群吧，群文件里都有，还有沙雕群友作陪，<(￣︶￣)↗[GO!]

来啦，传不上去可以试试我仓库里的clash Proxy。
![21FIF ~R~HL9$MR$W397}U5](https://user-images.githubusercontent.com/58871134/127137205-dbac8021-7bc8-4515-8585-a89947ea9d9f.jpg)

**Comment by GengGode** [comment]
没看懂clash Proxy，我该怎样才能用呢，大佬，赏个好友位吧 Q：2112028542
![@}OMI5TWEKHOXH7(CVUVGJ9](https://user-images.githubusercontent.com/47711102/127179665-f267514c-f28d-49cc-a8f3-ad828e571704.png)

**Comment by wmyfelix** [comment]
> 没看懂clash Proxy，我该怎样才能用呢，大佬，赏个好友位吧 Q：2112028542
> ![@}OMI5TWEKHOXH7(CVUVGJ9](https://user-images.githubusercontent.com/47711102/127179665-f267514c-f28d-49cc-a8f3-ad828e571704.png)

o((>ω< ))o您才是大佬。我不太用qq，一会我加一下。仓库里那个ClashConfigSharing是我用一些白嫖的机场做的配置文件，您用[clash](https://github.com/Dreamacro/clash)的[GUI](https://github.com/Fndroid/clash_for_windows_pkg)订阅导入即可.

**Comment by GengGode** [comment]
真没看懂咋用，我太菜了，救救

![](https://user-images.githubusercontent.com/47711102/127179665-f267514c-f28d-49cc-a8f3-ad828e571704.png)

**Comment by wmyfelix** [comment]
> 真没看懂咋用，我太菜了，救救
> 
> ![](https://user-images.githubusercontent.com/47711102/127179665-f267514c-f28d-49cc-a8f3-ad828e571704.png)
> 

额，就把gui下下来，然后导入订阅就行了。（原来只有我家移动宽带上GitHub要魔法上网

**Comment by GengGode** [comment]
流量也是魔法上网
这就去下

**Comment by GengGode** [comment]
太好了 lfs推上去了，牛
