### ISSUE TITLE
1.0.150出現錯誤提示

### ISSUE THREAD

**Issue by clcm8629** [GengGode/GenshinImpact_AutoMap#35]
![image](https://user-images.githubusercontent.com/69196409/127859678-b5294ab8-a69d-4c5f-a0df-df41986a6a08.png)
![image](https://user-images.githubusercontent.com/69196409/127859707-f309f524-8e29-4e27-aa28-f5e30f01efa5.png)
![image](https://user-images.githubusercontent.com/69196409/127859725-37522c17-818e-4a6b-9331-95a4eedda6e4.png)
![image](https://user-images.githubusercontent.com/69196409/127859757-118fb4c0-6b20-4ad0-b5eb-733ccc24dee5.png)

**Comment by GengGode** [comment]
应该是打包的时候打错了，我看一看

**Comment by GengGode** [comment]
很奇怪。release版的exe，打包的dll是debug版的，我再调整下

**Comment by GengGode** [comment]
已解决，为windeployqt命令添加-release
