### ISSUE TITLE
1

### ISSUE THREAD

**Issue by baize257** [GengGode/GenshinImpact_AutoMap#4]
可以出个教程么   怎么使用啊

**Comment by GengGode** [comment]
配置opencv4.5.0之后，在VS里生成启动第二个项目就行，Test_1的那个

**Comment by duig20** [comment]
> 配置opencv4.5.0之后，在VS里生成启动第二个项目就行，Test_1的那个

Please upload the finished project build to drive.google.com, I cannot download from xunlei :(

**Comment by HimekoX** [comment]
有蓝奏云的新版本吗 迅雷云盘太扯了:( 百度云都比他真实  微软E5可以白嫖25TB 速度也很不错

**Comment by Chocky1126** [comment]
> 配置opencv4.5.0之后，在VS里生成启动第二个项目就行，Test_1的那个

太好了  收藏了一个月  终于用上了

**Comment by GengGode** [comment]
目前可能能用，有问题及时反馈，我一直在线
