### ISSUE TITLE
游戏内部没有1090x1080分辨率，是写错了嘛？

### ISSUE THREAD

**Issue by bubuzi-code** [GengGode/GenshinImpact_AutoMap#6]
我win10，打开软件后启动原神，也没有任何反应

**Comment by HimuraYuu** [comment]
直接打开闪退 游戏后打开 不闪退但是界面不显示 点击闪一下

**Comment by GengGode** [comment]
不好意思啊，是写错了
已经改好了闪退问题，但是点一下闪一下的需要修改快捷方式，看readme的最后

**Comment by bubuzi-code** [comment]
那具体是多少分辨率？readme没有更新

**Comment by HimuraYuu** [comment]
可能是我没形容好  在开了游戏后打开他会没有界面 任务栏里有点他就是出来闪回去 出来闪回去 而且也没有读取我的信息 你说的是在开游戏之前开你的插件但是会闪退你说修复了 我在试试吧

**Comment by HimuraYuu** [comment]
> 不好意思啊，是写错了
> 已经改好了闪退问题，但是点一下闪一下的需要修改快捷方式，看readme的最后

修改好的是重新传云盘还是更新代码我们自己编译

**Comment by HimuraYuu** [comment]
试了一下 发现闪退是有改善但是过了一会还是闪 而且读取不到信息 小窗口 全屏我都试了应该不是分辨率的问题吧 作者大大加加油 改善一下兼容性问题 我觉得还是用mfc 写好一点

**Comment by GengGode** [comment]
emmm，兼容之后再整吧，现在主要是匹配有时候飘的厉害，神瞳识别有时候不准，我刚刚改了下，等会上传，这个能直接启动，不需要原神启动
