### ISSUE TITLE
release打包好的缺少一些依赖

### ISSUE THREAD

**Issue by FlyInWind1** [GengGode/GenshinImpact_AutoMap#7]
![图片](https://user-images.githubusercontent.com/29172747/108726598-91e6d100-7562-11eb-963e-492546201bd7.png)
还有
opencv_imgproc450.dll
opencv_featrue450.dll
opencv_world450.dll

**Comment by GengGode** [comment]
不是吧，我用的静态库啊，等会，我上传个动态库的，主要是这些东西太大了

**Comment by GengGode** [comment]
1.0.2，添加了依赖库，解压出来182MB

**Comment by FlyInWind1** [comment]
![图片](https://user-images.githubusercontent.com/29172747/108840448-55be7980-7611-11eb-8aa5-36944cebac39.png)
还是缺依赖。
我自己下了opencv，发现是源代码，不会windows程序。只能麻烦大佬测好了。。

**Comment by GengGode** [comment]
？？？不应该啊，我这就一台电脑，配了opencv的环境没法测emmm奇怪

**Comment by GengGode** [comment]
稍等，我看下是哪的问题

**Comment by GengGode** [comment]
这个是你却的那个文件先试下
[opencv_flann450.zip](https://github.com/GengGode/GenshinImpact_AutoMap/files/6029033/opencv_flann450.zip)

**Comment by FlyInWind1** [comment]
启动成功了，但是悬浮窗没有出现在游戏上方，-popupwindow 参数加了。
![图片](https://user-images.githubusercontent.com/29172747/108848239-b783e100-761b-11eb-81d7-7cb73fc3b565.png)
通过预览界面查看，似乎一直在这个地方

**Comment by FlyInWind1** [comment]
![图片](https://user-images.githubusercontent.com/29172747/108848484-003b9a00-761c-11eb-88a9-7687a24033d3.png)
通过预览界面查看，似乎一直在这个地方

**Comment by GengGode** [comment]
你如果按Win键的话原神会切出去吗，会的话就在原神里按alt+enter,再用

**Comment by GengGode** [comment]
离谱就是缺个dll

**Comment by FlyInWind1** [comment]
出来了，就是游戏上面出来了个边框，游戏界面整体下乘。强迫症总有点受不了。
这个抢最前窗口问题要还是跟官方反应下吧。
我讯飞输入法也经常弹不出界面。
但是windows10系统输入法是好的。

**Comment by GengGode** [comment]
???再按一下，可以切换，然后alt+T开自动追踪，悬浮窗会自动置顶，没做一直置顶，每隔一段时间置顶一下

**Comment by FlyInWind1** [comment]
可以了，不过开启自动追踪一直在抖动。
已经是很好的开端了，感谢大佬。
