### ISSUE TITLE
希望能够把窗户句柄设定独立出来

### ISSUE THREAD

**Issue by jason21415** [GengGode/GenshinImpact_AutoMap#8]
希望能够把窗户句柄设定独立出来
让ps端和手机模拟器也能用

ps端
窗户句柄为PS Remote Play
类名为WindowsForms10.Window.8.app.0.141b42a_r7_ad1

看挺实用的

![未命名](https://user-images.githubusercontent.com/57126581/109152563-a2878900-77a6-11eb-8450-5547a6f2715b.png)
![未命名2](https://user-images.githubusercontent.com/57126581/109152573-a4e9e300-77a6-11eb-8bb4-109a876c3253.png)

**Comment by GengGode** [comment]
emmm可以，我会尽快更新

**Comment by GengGode** [comment]
写好了还么测试，直接替换最新版的exe，Alt+F8弹出选择游戏的窗口
[GenshinImpact_AutoMap.zip](https://github.com/GengGode/GenshinImpact_AutoMap/files/6050258/GenshinImpact_AutoMap.zip)

**Comment by jason21415** [comment]
测试结果
自动追踪 X
添加自定义标记 O
大地图覆盖模式 X
弹窗选择原神游戏窗口 O
左键预设以及滚轮缩放地图显示 O
中键移动窗口位置 O
左键双击左上角派蒙退出 O
通过游戏内小地图，自动识别角色所在位置以及角色朝向 X
识别UID X

W10 1440 * 900 缩放100％ 全屏 版本1042
![1](https://user-images.githubusercontent.com/57126581/109376434-60258f80-78ff-11eb-9b61-63c36d80bcb5.png)
![2](https://user-images.githubusercontent.com/57126581/109376435-6156bc80-78ff-11eb-9e37-12b4a115661b.png)
![3](https://user-images.githubusercontent.com/57126581/109376437-61ef5300-78ff-11eb-80d3-0db95bca553d.png)
![5](https://user-images.githubusercontent.com/57126581/109376439-6287e980-78ff-11eb-85f3-965022cb26b1.png)

**Comment by GengGode** [comment]
简单实现了下，改成了判断当窗口不是原神的类的时候改为全屏截屏，最近在写神瞳识别，这块估计要等一段时间了
