### ISSUE TITLE
国际版无法使用

### ISSUE THREAD

**Issue by clcm8629** [GengGode/GenshinImpact_AutoMap#9]
国际版原神打开没反应，希望能添加对国际版的支持

**Comment by GengGode** [comment]
啊，不好意思啊，欠考虑了，emmm，我会尽快添加对国际版的支持

**Comment by GengGode** [comment]
我并不清楚国际版原神的应用名，如果可以的话希望提供一下

**Comment by sushank1** [comment]
GenshinImpact.exe
![image](https://user-images.githubusercontent.com/27129624/109199725-cb6b4680-77c5-11eb-8a53-4dff92e9d1e0.png)

**Comment by GengGode** [comment]
已经添加了支持，但是还没有测试

发布在release里了

**Comment by clcm8629** [comment]
感谢作者，但是我这里测试了悬浮窗还是没反应
甚至窗口也没有在最前

**Comment by GengGode** [comment]
啊，不是吧，emmm，稍等我想想，方便用spy++看下原神的类名吗
[spy++.zip](https://github.com/GengGode/GenshinImpact_AutoMap/files/6049782/spy%2B%2B.zip)

**Comment by GengGode** [comment]
[GenshinImpact_AutoMap.zip](https://github.com/GengGode/GenshinImpact_AutoMap/files/6049817/GenshinImpact_AutoMap.zip)
尝试修复了下，替换exe，应该是可以了

**Comment by clcm8629** [comment]
这个工具我不会用，不知道不是这个
![image](https://user-images.githubusercontent.com/69196409/109308739-6410cd80-787d-11eb-93c8-bd9236635f79.png)
![image](https://user-images.githubusercontent.com/69196409/109308780-71c65300-787d-11eb-8d01-9a6333b75d55.png)
![image](https://user-images.githubusercontent.com/69196409/109308892-915d7b80-787d-11eb-89f1-f7c37a627b8a.png)
![image](https://user-images.githubusercontent.com/69196409/109308919-96bac600-787d-11eb-877b-d89de4ed759a.png)

**Comment by GengGode** [comment]
上一个发的exe试了吗，有效果没，我写了可以选择游戏窗口的一个版本，正在测试，一会发给你，Alt+F8，唤出选择原神窗口的对话框

**Comment by clcm8629** [comment]
那个试过了，不行的

**Comment by GengGode** [comment]
emmm，那这样，spy++里按Alt+F3，在弹出的窗口里有个小圆圈，按住拖到原神上，截个图，麻烦你了

**Comment by clcm8629** [comment]
![image](https://user-images.githubusercontent.com/69196409/109310600-b652ee00-787f-11eb-9b08-9c391d8d0ffb.png)

**Comment by GengGode** [comment]
emmm ，最开始的版本应该是可以的，查找“原神“，支持国际版时通过系统语言判断的，只写了中文和英文两种，emmm我以为国际版的应用名不一样呢

**Comment by GengGode** [comment]
打开没反应可能是分辨率不支持，目前只做了键盘布局的1920*1080分辨率

**Comment by clcm8629** [comment]
呃...分辨率的确是用1920*1080，用了v1.041跟你刚传的都不行
有什么使用步骤吗？不管是先开原神跟GenshinImpact_AutoMap还是后开都不行

**Comment by GengGode** [comment]
先后没关系，emmm，什么症状，他应该会在检测到原神的时候自动移动到元素视野下方的位置，这就证明检测到了

**Comment by clcm8629** [comment]
我那时候在你早期传的版本（0.8.1）按了ALT+回车是可以让悬浮窗移动的小地图旁置顶
但是悬浮窗的地图是没反应的

**Comment by GengGode** [comment]
自动追踪需要Alt+T或者双击开启

**Comment by GengGode** [comment]
我想想先

**Comment by GengGode** [comment]
[GenshinImpact_AutoMap.zip](https://github.com/GengGode/GenshinImpact_AutoMap/files/6050240/GenshinImpact_AutoMap.zip)
试下这个Alt+F8选择原神窗口

**Comment by clcm8629** [comment]
![image](https://user-images.githubusercontent.com/69196409/109314607-878b4680-7884-11eb-9b9c-68611420ad52.png)
可以置顶了，但是地图还是没反应试了Alt+T跟双击不行

**Comment by GengGode** [comment]
地图右下角的魔法阵会变成蓝色的吗

**Comment by GengGode** [comment]
![Snipaste_2021-02-26_22-52-20](https://user-images.githubusercontent.com/47711102/109315269-55c6af80-7885-11eb-9ea2-fa197f88489c.png)
就像这样，双击之后

**Comment by GengGode** [comment]
可能是有边框不行，emmm，可以切成无边框试下，有边框没怎么测试つ﹏⊂

**Comment by clcm8629** [comment]
呃...刚又试了突然可以了，但是悬浮窗定位不准确而且一直在鬼畜..

**Comment by GengGode** [comment]
鬼畜是由于算法没滤波，emmm，主要是角色周围小图标太多会导致定位不准，因为用的是图像匹配，emmm很难处理

**Comment by GengGode** [comment]
能用了就行，这个可以定位为到了之后停止追踪，收集物品。本来是想做自动标记神瞳是否被收集的

**Comment by clcm8629** [comment]
那行吧，非常感謝你抽空協助我，期待後續的完善

**Comment by sushank1** [comment]
![image](https://user-images.githubusercontent.com/27129624/109324025-26f70c00-787a-11eb-8580-58389c80ece2.png)
Can you please add this alt f8 not working for me

**Comment by GengGode** [comment]
emmm ，Not Show this？
![Snipaste_2021-02-27_00-09-04](https://user-images.githubusercontent.com/47711102/109324796-210c2580-7890-11eb-903e-a92c4af68f01.png)

**Comment by sushank1** [comment]
even after this its not working

**Comment by GengGode** [comment]
1920*1080？
Just a minute. I'll send a new version

**Comment by GengGode** [comment]
i‘m sorry,that's a big file. I can't send it here，email OK？

**Comment by sushank1** [comment]
yes email is ok

**Comment by GengGode** [comment]
How will I get your email address

**Comment by sushank1** [comment]
sagarsushank12@gmail.com

**Comment by GengGode** [comment]
has been sent

**Comment by sushank1** [comment]
I didn't receive any email can you please check again? However if that doesn't work can you upload it somewhere and give link?

**Comment by GengGode** [comment]
sorry，google tall me
This message was blocked because its content presents a potential security issue. Please visit https://support.google.com/mail/?p=BlockedMessage to review our message content and attachment content guidelines. q21si1976915pld.72 - gsmtp 
i will try again

**Comment by GengGode** [comment]
Did you get the email ?

**Comment by sushank1** [comment]
I did not get any email.

**Comment by GengGode** [comment]
you could download v1.0.4.2，

I uploaded it
